scrape_configs:
  - job_name: Confluent Cloud
    scrape_interval: 1m
    scrape_timeout: 1m
    honor_timestamps: true
    static_configs:
      - targets:
        - api.telemetry.confluent.cloud
    scheme: https
    basic_auth:
      username: FTWXXDYSWOZBOZXD
      password: 0MuvumNZb1ux9NuC3kD7rMT4gMJhWPwB72zG0FyQ+0nzTTF6EqkCv1U+/dbUzcoG
    metrics_path: /v2/metrics/cloud/export
    params:
      resource.kafka.id: [lkc-72nwj, lkc-rqnd1]       
      resource.connector.id: []    
      resource.ksql.id: []
      resource.schema_registry.id: [lsrc-3x75j]
          